
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'jhimetrics',
            'jhiopenapigroups',
            'logfile',
            'loggers',
            'prometheus',
            'threaddump',
            'caches',
            'liquibase',
          ]
  endpoint:
    health:
      show-details: when_authorized
      roles: 'SUPER-ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true

spring:
  application:
    name: mstemplate
  main:
    allow-bean-definition-overriding: true
  cloud:
    # if you need to start service without consul, use next configuration and disable consul by spring.cloud.consul.enabled
#    discovery:
#      client:
#        simple:
#          instances:
#            config:
#              - instanceId: config
#                serviceId: config
#                host: localhost
#                port: 8084
    consul:
      enabled: true
      discovery:
        healthCheckPath: /management/health
        instanceId: mstemplate:${spring.application.instance-id:${random.value}}
        service-name: mstemplate
      config:
        watch:
          enabled: false
    stream:
      kafka:
        binder:
          brokers: ${spring.kafka.bootstrap-servers}
          autoCreateTopics: false
  profiles:
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
  jmx:
    enabled: false # TODO false ot true ?
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.model.generator_name_as_sequence_name: false
      hibernate.jdbc.time_zone: UTC
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty
  kafka:
    bootstrap-servers: localhost:9092
#  To start using feign client with authentication, use this configuration and provide correct
#  token-uri, client-id and client-secret
  security:
    oauth2:
      client:
        provider:
          uaa:
            token-uri: http://localhost:9999/oauth/token
        registration:
          uaa:
            authorization-grant-type: client_credentials
            client-id: internal
            client-secret: internal

server:
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  show-actuator: true

xm-config:
  enabled: true
  #configMode: FILE
  #configDirPath:

# Properties to be exposed on the /info management endpoint
info:
  # Comma separated list of profiles that will trigger the ribbon to show
  display-ribbon-on-profiles: 'dev'

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  clientApp:
    name: 'mstemplateApp'
  api-docs:
    default-include-pattern: ${server.servlet.context-path:}/api/**
    management-include-pattern: ${server.servlet.context-path:}/management/**
    title: Mstemplate API
    description: Mstemplate API documentation
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:"

application:
  specification-path-pattern: /config/tenants/{tenantName}/${spring.application.name}/example-of-microservice-spec.yml
  tenant-ignored-path-list: /v2/api-docs, /api/profile-info, /swagger-resources/configuration/ui, /management/health, /management/prometheus
  timeline-ignored-http-methods:

  timelines-enabled: false
  kafka-enabled: true
  scheduler-enabled: false

  tenant-with-creation-access-list: XM, MANAGER
  kafka-system-topic: system_topic
  kafka-system-queue: system_queue
  kafka-metadata-max-age: 60000 #in milliseconds
  kafkaHealth:
    enabled: true
